// Default per-page SEO copy. Admin overrides (seo.pages[path]) merge on top of these.
export const SEO_ROUTES = [
  { path: "/", label: "Home", title: "Managed IT, Cybersecurity & Cloud Services", description: "Complete oversight of your technology environment—proactive monitoring, infrastructure management, and strategic guidance to keep operations secure and resilient." },
  { path: "/about", label: "About Us", title: "About Intrinsic Technology", description: "A women-owned and minority-owned managed service provider in New York City delivering accountable, coordinated technology services." },
  { path: "/resources", label: "Resources", title: "Resources, Insights & Case Studies", description: "Practical insights, service briefs, and client case studies to help you make better technology decisions." },
  { path: "/careers", label: "Careers", title: "Careers at Intrinsic Technology", description: "Join a technology team focused on security, reliability, and real client outcomes." },
  { path: "/contact", label: "Contact", title: "Talk to an Expert", description: "Get in touch with Intrinsic Technology to discuss managed IT, cybersecurity, cloud, and AI services." },
  { path: "/privacy-policy", label: "Privacy Policy", title: "Privacy Policy", description: "How Intrinsic Technology collects, uses, and protects your information." },
  { path: "/terms-of-service", label: "Terms of Service", title: "Terms of Service", description: "The terms governing use of the Intrinsic Technology website." },
  { path: "/security-risk-assessment", label: "Security Risk Assessment", title: "Security Risk Assessment", description: "Identify gaps and prioritize remediation with a structured security risk assessment." },
  { path: "/services/ai", label: "AI Services", title: "AI Services & Automation", description: "Adopt AI responsibly with readiness assessments, managed AI, and governance aligned to your business." },
  { path: "/services/ai-readiness-assessment", label: "AI Readiness Assessment", title: "AI Readiness Assessment", description: "A comprehensive view of your AI readiness across business, data, security, governance, and organizational preparedness." },
  { path: "/services/managed-ai", label: "Managed AI", title: "Managed AI", description: "Ongoing management of AI tools, access, and governance so your organization benefits safely." },
  { path: "/services/ai-governance-compliance", label: "AI Governance & Compliance", title: "AI Governance & Compliance", description: "Establish policy, oversight, and controls for responsible AI adoption." },
  { path: "/services/cybersecurity", label: "Cybersecurity", title: "Cybersecurity Services", description: "Coordinated security management across users, devices, networks, cloud, applications, and data." },
  { path: "/services/threat-detection-response", label: "Threat Detection & Response", title: "Threat Detection & Response", description: "Continuous monitoring, detection, and rapid response to security threats." },
  { path: "/services/identity-endpoint-security", label: "Identity & Endpoint Security", title: "User, Identity & Endpoint Security", description: "Protect identities and endpoints with layered controls and patch compliance." },
  { path: "/services/network-perimeter-security", label: "Network & Perimeter Security", title: "Network & Perimeter Security", description: "Secure your network edge with firewalls, segmentation, and monitoring." },
  { path: "/services/security-monitoring-siem", label: "Security Monitoring & SIEM", title: "Security Monitoring & Analytics (SIEM)", description: "Centralized logging, correlation, and analytics for faster threat insight." },
  { path: "/services/security-assessments", label: "Security Assessments", title: "Security Assessments & Vulnerability Management", description: "Regular assessments and vulnerability management to reduce risk." },
  { path: "/services/security-governance-compliance", label: "Security Governance & Compliance", title: "Security Governance & Compliance", description: "Governance aligned to NIST CSF, HIPAA, NYDFS, and SOC 2." },
  { path: "/services/networking", label: "Networking", title: "Networking Services", description: "Design, deployment, and management of reliable business networks." },
  { path: "/services/cloud", label: "Cloud", title: "Cloud Services", description: "Cloud infrastructure, migration, and management built for resilience." },
  { path: "/services/cloud-infrastructure-migration", label: "Cloud Infrastructure & Migration", title: "Cloud Infrastructure & Migration", description: "Migrate and modernize on Microsoft Azure and Microsoft 365 without the chaos." },
  { path: "/services/backup-disaster-recovery", label: "Backup & Disaster Recovery", title: "Backup & Disaster Recovery", description: "Protect your data and operations with tested backup and recovery." },
  { path: "/services/managed-it", label: "Managed IT", title: "Managed IT Services", description: "Complete oversight of your IT environment with proactive support and management." },
  { path: "/services/co-managed-it", label: "Co-Managed IT", title: "Co-Managed IT", description: "Extend your internal IT team with coordinated managed services." },
  { path: "/services/remote-monitoring-management", label: "Remote Monitoring & Management", title: "Remote Monitoring & Management", description: "24/7 monitoring and management of devices and systems." },
  { path: "/services/microsoft-365", label: "Microsoft 365", title: "Microsoft 365 Services", description: "Deploy, secure, and manage Microsoft 365 for productivity and compliance." },
  { path: "/services/vcio-vciso", label: "vCIO & vCISO", title: "vCIO & vCISO", description: "Strategic technology and security leadership that guides priorities and investment." },
  { path: "/industries", label: "Industries", title: "Industries We Serve", description: "Technology services tailored to healthcare, financial, legal, construction, nonprofit, and professional services." },
  { path: "/industries/construction", label: "Construction", title: "IT for Construction", description: "Technology that extends to the field for construction and manufacturing." },
  { path: "/industries/professional-services", label: "Professional Services", title: "IT for Professional Services", description: "Secure, reliable technology for professional services firms." },
  { path: "/industries/financial-services", label: "Financial Services", title: "IT for Financial Services", description: "Compliance-ready managed IT and security for financial services." },
  { path: "/industries/non-profit", label: "Non-Profit", title: "IT for Non-Profits", description: "Affordable, dependable technology for nonprofit organizations." },
  { path: "/industries/healthcare", label: "Healthcare", title: "IT for Healthcare", description: "HIPAA-aligned managed IT and security for healthcare providers." },
];

export const SEO_ROUTE_MAP = SEO_ROUTES.reduce((m, r) => { m[r.path] = r; return m; }, {});
